name: Build Dokerfile
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert repository name to lowercase
        id: lowercase-repo
        run: echo "::set-output name=repository::$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.lowercase-repo.outputs.repository }}:latest
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
